name: fav car workflow

on:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
   
jobs:
  # 1st job
  carname:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: car_name_job
        run: echo "My favourite car is Redbull"
        shell: bash
