name: Hello world workflow

on:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
   
jobs:
  # 1st job
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello_world_job
        run: echo "Hello world"
        shell: bash
   
  # 2nd job 
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Good bye cruel world"
        shell: bash
      
   
