name: Hello world workflow

# on specifies the events which will trigger this workflow
on:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
   workflow_dispatch:
   
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello_world_job
        run: echo "Hello world"
        shell: bash
      
   
