name: 'Tweet when labeled'

on:
  issues:
    types: labeled
    
permissions:
  contents: read
  issues: write
  
jobs:
  action:
  if: ${{ github.event.label.name == 'bug' }}
  runs-on: ubuntu-latest
  steps:
        - name: Print Output
          uses: ethomson/send-tweet-action@v1
          with:
            status: "HeLLLo Twitter, Checkout this issue - ${{ github.event.issue.html_url }} with the title ${{ github.event.issue.title }}"
            consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
            consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
            access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
            access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  
